"""Update data model visitCount

Revision ID: 1b7d69f6e805
Revises: f447852440a1
Create Date: 2026-01-17 17:57:49.416282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7d69f6e805'
down_revision: Union[str, Sequence[str], None] = 'f447852440a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Image', sa.Column('viewCount', sa.Integer(), nullable=False))
    op.add_column('Image', sa.Column('downloadCount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Image', 'downloadCount')
    op.drop_column('Image', 'viewCount')
    # ### end Alembic commands ###
