"""Remove processedUrl column

Revision ID: 26b8dc60b118
Revises: b6c4ef0fb49f
Create Date: 2026-01-17 06:19:47.888555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b8dc60b118'
down_revision: Union[str, Sequence[str], None] = 'b6c4ef0fb49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Image', 'processedUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Image', sa.Column('processedUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
