"""Add LINK

Revision ID: 624faca197cd
Revises: 130ca4da3dc6
Create Date: 2026-01-17 05:53:46.500437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624faca197cd'
down_revision: Union[str, Sequence[str], None] = '130ca4da3dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Face', 'User', ['userId'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Face', type_='foreignkey')
    # ### end Alembic commands ###
