"""init

Revision ID: ccb608d45b15
Revises: 1d4e5163961d
Create Date: 2026-01-16 12:23:57.960196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb608d45b15'
down_revision: Union[str, Sequence[str], None] = '1d4e5163961d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('googleId', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatarUrl', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='Role'), nullable=False),
    sa.Column('profileData', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('googleId')
    )
    op.create_index('User_email_idx', 'User', ['email'], unique=False)
    op.create_index('User_googleId_idx', 'User', ['googleId'], unique=False)
    op.create_table('UserFaceReference',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('qdrantId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrantId'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('Image',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('originalUrl', sa.String(), nullable=False),
    sa.Column('processedUrl', sa.String(), nullable=True),
    sa.Column('storagePath', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'READY', 'ERROR', name='ImageStatus'), nullable=False),
    sa.Column('imageData', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Image_status_idx', 'Image', ['status'], unique=False)
    op.create_index('Image_userId_idx', 'Image', ['userId'], unique=False)
    op.create_table('Face',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('imageId', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('qdrantId', sa.String(), nullable=True),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('assignedBy', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imageId'], ['Image.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrantId')
    )
    op.create_index('Face_imageId_idx', 'Face', ['imageId'], unique=False)
    op.create_index('Face_userId_idx', 'Face', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Face_userId_idx', table_name='Face')
    op.drop_index('Face_imageId_idx', table_name='Face')
    op.drop_table('Face')
    op.drop_index('Image_userId_idx', table_name='Image')
    op.drop_index('Image_status_idx', table_name='Image')
    op.drop_table('Image')
    op.drop_table('UserFaceReference')
    op.drop_index('User_googleId_idx', table_name='User')
    op.drop_index('User_email_idx', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
