"""Add similarity field to Face

Revision ID: f447852440a1
Revises: 1e7b5476bdd9
Create Date: 2026-01-17 08:19:20.827658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f447852440a1'
down_revision: Union[str, Sequence[str], None] = '1e7b5476bdd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Face', sa.Column('similarity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Face', 'similarity')
    # ### end Alembic commands ###
